### PR TITLE
added adventureland template frontierland template and modified tomor…

### PR DESCRIPTION
**Pull request by therealrmac**
…rowland

### CODE REVIEW

**Review by elizawmeeks — COMMENTED** [review]
👍

**Review by chazhenricks — COMMENTED** [review]
add a line at end of each document. 

you can open sublime text global preferences and paste this in and it will do it automatically. 

"ensure_newline_at_eof_on_save": true,

**Comment by NickHerron101** [comment]
👍

**Comment by NickHerron101** [comment]
wait no need for these

**Pull request closed without merging**
