### PR TITLE
Chazland

### PR DESCRIPTION
**Pull request by chazhenricks**
Merged new master into branch. 
Colors change on area select. 
Ticker works.

### CODE REVIEW

**Comment by therealrmac** [comment]
[https://img.memesuper.com/d606c78801fdb47a20068f4bbc79847d_i-like-it-memes-memesuper-thor-i-like-it-meme_378-363.jpeg](url)

**Comment by therealrmac** [comment]
https://img.memesuper.com/d606c78801fdb47a20068f4bbc79847d_i-like-it-memes-memesuper-thor-i-like-it-meme_378-363.jpeg

**Comment by augsismyburger** [comment]
Shweet 👍

**Comment by elizawmeeks** [comment]
this is a nice comment about your adequate efforts

**Comment by NickHerron101** [comment]
👍

**Pull request merged**
