### PR TITLE
Elizaland timetick

### PR DESCRIPTION
**Pull request by elizawmeeks**

### CODE REVIEW

**Comment by therealrmac** [comment]
I thought i had broken it, but lo.

**Comment by chazhenricks** [comment]
-When area clicked - event listener for clock disabled until user clicks on area a second time. 
-Might also consider making it slide out a few more pixels for easier readability.

**Comment by augsismyburger** [comment]
👍  Would also like to see sidebar be a bit bigger.

**Comment by chazhenricks** [comment]
Looks good!

**Pull request merged**
