### PR TITLE
commented my code, cleaned stuff up

### PR DESCRIPTION
**Pull request by elizawmeeks**
Should be no functional changes.

### CODE REVIEW

**Comment by therealrmac** [comment]
https://img.memesuper.com/d606c78801fdb47a20068f4bbc79847d_i-like-it-memes-memesuper-thor-i-like-it-meme_378-363.jpeg

**Comment by augsismyburger** [comment]
👍

**Comment by chazhenricks** [comment]
I looked. And I liked it.

**Comment by NickHerron101** [comment]
👍

**Pull request merged**
