### PR TITLE
Ryan land

### PR DESCRIPTION
**Pull request by therealrmac**

### CODE REVIEW

**Comment by NickHerron101** [comment]
looks good, just need to add Toon Town to the dropdown for Select Area

**Comment by elizawmeeks** [comment]
looks good

**Comment by augsismyburger** [comment]
👍  maybe some border radius on the zoomed images

**Comment by therealrmac** [comment]
dont merge mine yet plz

**Comment by chazhenricks** [comment]
DOPE

**Comment by therealrmac** [comment]
good to go

**Pull request closed without merging**
